---
# More about feed: https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/
name: Build image for BPi-R4 with MTK feed - alt

on:
  workflow_dispatch:
    inputs:
      DEVICE_CONFIG:
        description: "Device configuration selection: <none> or poe (default: non-poe)"
        required: true
        type: choice
        default: 'non-poe'
        options:
          # - poe
          - non-poe

env:
  REMOTE_REPOSITORY: openwrt/openwrt
  # REMOTE_BRANCH: openwrt-24.10
  REMOTE_BRANCH: 68bf4844a1cbc9f404f6e93b70a2657e74f1dce9
  RELEASE_PREFIX: bpi-r4-mtk
  DEVICE_CONFIG: ${{ inputs.DEVICE_CONFIG == 'poe' && 'configs/mediatek/mt7988a/bpi-r4-poe' || 'configs/mediatek/mt7988a/bpi-r4' }}

jobs:
  check_commits:
    name: Check Commits
    runs-on: ubuntu-24.04
    outputs:
      latest_commit_sha: ${{ steps.get_sha.outputs.latest_commit_sha }}
    steps:
      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}

      - name: Get the latest commit SHA
        id: get_sha
        run: |
          echo "latest_commit_sha=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "latest_commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  build:
    name: Build BPI-R4 with MTK feed - alt
    needs: [check_commits]
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget curl zstd \
            git

      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}

      - name: Clone mediatek feed
        run: |
          git clone https://git01.mediatek.com/openwrt/feeds/mtk-openwrt-feeds mtk-openwrt-feeds;
          cd mtk-openwrt-feeds;
          git checkout 42df09d4cf568c795e71427668fae0eea4f112c5

      - name: Clone woziwrt repo
        run: |
          git clone https://github.com/woziwrt/bpi-r4-mtk

      - name: Clone my repo
        run: |
          git clone https://github.com/danpawlik/bpi-r4-mtk my-bpi-r4-mtk

      - name: Recreate patches dir
        run: |
          rm -rf package/firmware/wireless-regdb/patches;
          rm -rf mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/files/package/firmware/wireless-regdb/patches;
          mkdir -p package/firmware/wireless-regdb/patches;
          mkdir -p mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/files/package/firmware/wireless-regdb/patches;

      - name: Copy woziwrt patches
        run: |
          cp bpi-r4-mtk/my_files/500-tx_power.patch mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/files/package/firmware/wireless-regdb/patches
          cp bpi-r4-mtk/my_files/regdb.Makefile package/firmware/wireless-regdb/Makefile
          cp bpi-r4-mtk/my_files/rules mtk-openwrt-feeds/autobuild/unified
          cp bpi-r4-mtk/my_files/mt7988a-rfb-spim-nand-nmbm.dtso target/linux/mediatek/files-6.6/arch/arm64/boot/dts/mediatek
          cp bpi-r4-mtk/my_files/mt7981-rfb-spim-nor.dtso target/linux/mediatek/files-6.6/arch/arm64/boot/dts/mediatek
          cp bpi-r4-mtk/my_files/mt7988d-rfb.dts target/linux/mediatek/files-6.6/arch/arm64/boot/dts/mediatek
          cp bpi-r4-mtk/my_files/mt7988a-rfb-spidev.dtso target/linux/mediatek/files-6.6/arch/arm64/boot/dts/mediatek

          # cp bpi-r4-mtk/my_files/750-mtk-eth-add-jumbo-frame-support-mt7998.patch target/linux/mediatek/patches-6.6
          # cp bpi-r4-mtk/my_files/0001-mt76-w-package-makefile.patch mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/patches-base/0001-mt76-package-makefile.patch
          # cp bpi-r4-mtk/my_files/0004-mac80211-w-package-makefile.patch mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/patches-base/0004-mac80211-package-makefile.patch


          cp bpi-r4-mtk/my_files/ethtool/Makefile package/network/utils/ethtool/Makefile
          # cp -r bpi-r4-mtk/my_files/0008-wozi-mac80211-Support-EHT-1024-aggregation-size-in-T.patch mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/files/package/kernel/mac80211/patches/subsys/0008-wifi-mac80211-Support-EHT-1024-aggregation-size-in-T.patch
          # cp -r bpi-r4-mtk/my_files/0008-wozi-mac80211-Support-EHT-1024-aggregation-size-in-T.patch mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7988_wifi7_mac80211_mlo/package/kernel/mac80211/patches/subsys/0008-wifi-mac80211-Support-EHT-1024-aggregation-size-in-T.patch
          cp bpi-r4-mtk/my_files/999-2709-net-ethernet-mtk_eth_soc-add-rss-lro-reg.patch mtk-openwrt-feeds/autobuild/unified/global/24.10/files/target/linux/mediatek/patches-6.6/
          cp bpi-r4-mtk/my_files/999-2710-net-ethernet-mtk_eth_soc-add-rss-support.patch mtk-openwrt-feeds/autobuild/unified/global/24.10/files/target/linux/mediatek/patches-6.6/
          cp bpi-r4-mtk/my_files/0006-arch-arm64-dts-mt7988a-add-adma-intrrupts.patch mtk-openwrt-feeds/autobuild/unified/global/24.10/patches-base/
          cp -r bpi-r4-mtk/my_files/mediatek/*.* mtk-openwrt-feeds/autobuild/unified/global/24.10/files/target/linux/mediatek/files-6.6/drivers/net/ethernet/mediatek/


      - name: Make sed
        run: |
          sed -i 's/CONFIG_PACKAGE_perf=y/# CONFIG_PACKAGE_perf is not set/' \
              mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/defconfig \
              mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7988_wifi7_mac80211_mlo/.config \
              mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7986_mac80211/.config

          sed -i 's/CONFIG_PACKAGE_kmod-thermal=y/# CONFIG_PACKAGE_kmod-thermal is not set/' \
              mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7988_wifi7_mac80211_mlo/.config \
              mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7981_mac80211/.config \
              mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7986_mac80211/.config


      - name: Run Mediatek prepare
        run: |
          bash ./mtk-openwrt-feeds/autobuild/unified/autobuild.sh filogic-mac80211-mt7988_rfb-mt7996 prepare log_file=make

      - name: Print current config file
        run: cat .config

      - name: Replace current config with my config
        run: |
          cp my-bpi-r4-mtk/configs/my.config .config

      - name: Run defconfig
        run: |
          make defconfig

      - name: Print again config file
        run: cat .config

      - name: Build the firmware image
        run: make -j $(nproc) download world

      - name: Compress all packages
        run: |
          tar caf bin/targets/mediatek/filogic/packages.tar.gz bin/targets/mediatek/filogic/packages

      - name: Package output
        run: tar -cvf bpi_r4-images.tar bin/targets/mediatek/filogic

      - name: Add config file
        run: cp .config  bin/targets/mediatek/filogic/config-full

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bpi_r4-images
          path: bpi_r4-images.tar

  release:
    name: Create release
    needs: [build, check_commits]
    if: needs.build.result == 'success'
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bpi_r4-images

      - name: Extract artifacts
        run: tar xf bpi_r4-images.tar

      - name: Get current date
        run: echo "RELEASE_DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@master
        with:
          files: bin/targets/mediatek/filogic/*
          tag_name: ${{ env.RELEASE_PREFIX }}-${{ env.REMOTE_BRANCH }}-${{ env.RELEASE_DATE }}
          name: OpenWRT BPI-R4 with MTK Feed ${{ inputs.DEVICE_CONFIG == 'poe' && 'POE' || '' }} - ${{ env.RELEASE_DATE }}
          body: |
            Updated prebuilt images for BPI-R4 ${{ inputs.DEVICE_CONFIG == 'poe' && 'PoE version' || '' }}  with MTK feed.

            Build Commit: ${{ needs.check_commits.outputs.latest_commit_sha }}

      - name: Clean up old releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 5
          delete_tags: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
